// Ported from mcp/src/lib/pantry-staples.ts (2026-07). mcp/ stays a separate consumer.
export const COMMON_PANTRY_STAPLES = [
  "salt",
  "pepper",
  "black pepper",
  "kosher salt",
  "sea salt",
  "olive oil",
  "extra virgin olive oil",
  "vegetable oil",
  "canola oil",
  "cooking spray",
  "butter",
  "unsalted butter",
  "flour",
  "all-purpose flour",
  "sugar",
  "brown sugar",
  "powdered sugar",
  "garlic powder",
  "onion powder",
  "paprika",
  "smoked paprika",
  "cumin",
  "ground cumin",
  "chili powder",
  "oregano",
  "dried oregano",
  "basil",
  "dried basil",
  "thyme",
  "dried thyme",
  "rosemary",
  "bay leaf",
  "bay leaves",
  "red pepper flakes",
  "crushed red pepper",
  "cayenne pepper",
  "cinnamon",
  "ground cinnamon",
  "nutmeg",
  "soy sauce",
  "vinegar",
  "white vinegar",
  "apple cider vinegar",
  "balsamic vinegar",
  "rice vinegar",
  "honey",
  "mustard",
  "dijon mustard",
  "ketchup",
  "mayonnaise",
  "hot sauce",
  "worcestershire sauce",
  "baking soda",
  "baking powder",
  "vanilla extract",
  "chicken broth",
  "beef broth",
  "vegetable broth",
  "tomato paste",
  "cornstarch",
  "sesame oil",
];
